<?php


class RefAutoEmailTypeModel extends CFormModel
{
    CONST ADD_PARTNER = 1;
    CONST INVENTORY_CRITICAL_LEVEL = 2;
    CONST INVENTORY_OUTOFSTOCK = 3;
    CONST REWARDS_AVAILMENT_NOTIFICATION = 4;
        
}
?>
