<?php

/*
 * @author : owliber
 * @date : 2013-06-06
 */

class AuditFunctions extends BaseEntity
{
    CONST LOGIN = 1;
    CONST LOGOUT = 2;
    CONST UPDATE_PROFILE = 3;
    CONST VERIFY_EMAIL = 4;
    CONST PROCESS_POINTS = 5;
    CONST TRANSFER_POINTS = 6;
    CONST MIGRATE_OLD = 7;
    CONST MIGRATE_TEMP = 8;
    CONST BAN_PLAYER = 9;
    CONST UNBAN_PLAYER = 10;
    CONST LOCKED_ACCOUNT = 11;
    CONST ADMIN_PLAYER_PROFILE = 12;
    CONST ADMIN_UPDATE_MEMBERSHIP_PROFILE = 13;
    CONST ADMIN_REPORTS_TRANSACTION_HISTORY = 14;
    CONST ADMIN_REPORTS_BANNED_PLAYERS = 15;
    CONST CASHIER_PLAYER_PROFILE = 16;
    CONST CASHIER_UPDATE_MEMBERSHIP_PROFILE = 17;
    CONST CASHIER_REDEMPTION = 18;
    CONST CS_PLAYER_PROFILE = 19;
    CONST CS_UPDATE_MEMBERSHIP_PROFILE = 20;
    CONST OPERATIONS_PLAYER_PROFILE = 21;
    CONST OPERATIONS_UPDATE_MEMBERSHIP_PROFILE = 22;
    CONST OPERATIONS_TRANSACTION_HISTORY = 23;
    CONST OPERATIONS_BANNED_PLAYERS = 24;
    CONST PAGCOR_BAN_PLAYERS = 25;
    CONST PAGCOR_UNBAN_PLAYERS = 26;
    CONST PAGCOR_BANNED_PLAYERS = 27;
    CONST PLAYER_REGISTRATION = 28;
    CONST PLAYER_EMAIL_VERIFICATION = 29;
    CONST PLAYER_ACCOUNT_VERIFICATION = 30;
    CONST PLAYER_UPDATE_MEMBERSHIP_PROFILE = 31;
    CONST MARKETING_REDEMPTION = 36;
    CONST PLAYER_REDEMPTION = 37;
    CONST MARKETING_ADD_REWARD_ITEM = 38;
    CONST MARKETING_UPDATE_REWARD_ITEM = 42;
    CONST MARKETING_ADD_PROMO = 39;
    CONST MARKETING_UPDATE_PROMO = 40;
    CONST MARKETING_CHANGE_PROMO_STATUS = 41;
    CONST MARKETING_RED_CARD_TRANSFERRING = 43;
    CONST TERMINATE = 44;
    CONST ACTIVATE = 45;
    CONST MANUAL_REDEMPTION_FULFILLMENT = 46;
    CONST PLAYER_ITEM_REDEMPTION = 47;
    CONST CASHIER_ITEM_REDEMPTION = 48;
    CONST PLAYER_BLACKLISTING = 49;
    CONST UPDATE_BLACKLISTED_PLAYER = 50;
    CONST REMOVE_BLACKLISTED_PLAYER = 51;
    CONST PLAYER_CLASSIFICATION_ASSIGNMENT = 52;
    CONST MANUAL_CASINO_UB_ASSIGNMENT = 53;
    CONST CHANGE_PLAYER_PASSWORD = 54;
    CONST BATCH_PLAYER_CLASSIFICATION_MAPPING = 65;
    CONST VIP_LEVEL_MANAGEMENT = 66;
    
    public function AuditFunctions()
    {
        $this->ConnString = "membership";
        $this->TableName = "ref_auditfunctions";
        $this->Identity = "AuditFunctionID";
    }
    
    public function getAuditFunctions($auditfunctionid)
    {
        $query = "SELECT * FROM " . $this->TableName .
                 " WHERE AuditFunctionID = $auditfunctionid";
        
        $result = parent::RunQuery($query);
        return $result[0]['AuditFunctionName'];
    }
}

?>
